### ISSUE TITLE
机械臂末端3关节位置q基本不发生变动

### ISSUE THREAD

**Issue by nanyangnuan** [skywoodsz/qm_control#19]
感谢分享。
请问下，我在rviz变更目标位置的时候发现机械臂的靠近末端执行器的三个关节基本不发生运动。请问我如果想让这块约束减少，应该修改哪方面的程序。提前感谢

**Comment by skywoodsz** [comment]
@nanyangnuan 
It's a good performance.  The motion of the quadruped replaces the motion of the third joint of the manipulator. Otherwise, when the target is far away, the motion of the third joint will cause the manipulator to fall into sigularity. So I don't recommend relaxing the third joint restriction.

If you want to do that, you can modify the weight value and joint speed limit of the third joint.
